### ISSUE TITLE
empty console.logs output

### ISSUE THREAD

**Issue by matthiasg** [MatAtBread/browserify-nodent#1]
i have been using it now and still am. first feedback using it from gulp, it produces a number of console.log statements (1 or 2 pages of empty lines). not sure whether its nodent or the browserify wrapper though.

**Comment by MatAtBread** [comment]
I think the source is the wrapper that (incorrectly) logged(error.stack), which for syntax errors is set to "". This should go away when I merge in your PR.

**Comment by matAtWork** [comment]
This should all be fixed in the latest version. Your question about using annotations and other ES6 features is probably fixed by using 'fast-async' which is a plugin for Babel, and so (hopefully) leaves unknown nodes untouched - it works with JSX.
